### ISSUE TITLE
Arc has no type/“friendly name” in serialosc device list

### ISSUE THREAD

**Issue by barnabywalters** [TheSlowGrowth/MonomeArcClone#1]
When I plug a monome grid 128 into my computer and request a device list from serialosc with `/serialosc/list`, it returns a list of devices, each with three fields: serial number, “type” and port. For my grid, these values are: `m0000033`, `monome 128` and whatever port serialosc has assigned to the device.

When I plug in my arc clone and list, I get the serial number I programmed the FTDI chip with and a port, but the “type” field is an empty string.

This string is pretty useful for people choosing between multiple devices, and it would be nice to have it look the same as whatever shows up when listing an arc2/4 from monome. I had a look through the source of both the arc clone firmware and serialosc to try to figure out what the suitable text would be and how to add this, but couldn’t figure it out. Within serialosc, this field seems to be referred to as “friendly_name”, but I can’t figure out exactly where it comes from.

**Comment by TheSlowGrowth** [comment]
I took a look at the code. It seems the friendly_name is assigned with the function `monome_get_friendly_name()` which is defined in libmonome. Take a look at `mext.c`, line 454, this is where it is assigned during the device lookup. Apparently, the friendly name is whatever the device answers to the `Query_ID` command. In the clone, I had no clue what the ID may be for, so right now, I simply answer with a bunch of zeros - which is an empty string. 

I added a quick fix on the `friendly_name_fix` branch: b79d19d can you try that out? It should report `arc2` or `arc4` as the friendly_name. I don't have time to check it myself right now, I hope this helps anyway.

**Comment by TheSlowGrowth** [comment]
fixed with 65f6bdfd8ddd41d7a69304fbd2a3c681454ebe6e
